server: 
   port: 8888 
spring: 
  profiles: 
    active: native 
  cloud: 
     config: 
       server: 
           native: 
              searchLocations: file://Users/c.aguilar.rodriguez/git/configuration-server/configuration-server/src/main/resources/config/racesservice.yml