server: 
   port: 8888 
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xtianaguilar/config-repo.git
          username: xtianaguilar
          password: "Rod#rod1" 
          search-paths: racesservice
#spring: 
#  profiles: 
#    active: native 
#  cloud: 
#     config: 
#       server: 
#           native: 
#              searchLocations: file://Users/c.aguilar.rodriguez/git/configuration-server/configuration-server/src/main/resources/config/racesservice.yml