tracer.property: "I AM THE DEV CONFIG"
spring.jpa.database: "MySQL"
spring.datasource.platform: "MySQL"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost:3306/races?useSSL=false"
spring.datasource.username: "root"
spring.datasource.password: "dimarzio"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL8Dialect"